<?php

namespace app\web\controller;

use think\console\command\make\Controller;
use think\Db;


class Base extends \think\Controller
{

    public function __construct($name = null)
    {


        parent::__construct($name);
    }


    public function _initialize()
    {

        $res = Db('config')->select();
        // dump($res);
        $this->assign('config',$res);
        if($res[4]['value']==0){


            die('网站正在维护中，请稍后再来');
        }
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


}